{ ... }:
{
  imports = [
    ./bat.nix
    ./browser.nix
    ./btop.nix
    ./cava/cava.nix
    ./discord/discord.nix
    ./fastfetch/fastfetch.nix
    ./fzf.nix
    ./git.nix
    ./gtk.nix
    ./hyprland
    ./hyprlock/hyprlock.nix
    ./kitty.nix
    ./nvim.nix
    ./obsidian.nix
    ./p10k/p10k.nix
    ./packages.nix
    ./rofi.nix
    ./scripts/scripts.nix
    ./starship.nix
    ./stremio.nix
    ./swaylock.nix
    ./swaync/swaync.nix
    ./swayosd.nix
    ./vod.nix
    ./vscodium.nix
    ./waybar
    ./waypaper.nix
    ./xdg-mimes.nix
    ./yazi.nix
    ./zsh
  ];
}
